---
repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language: python
        language_version: python3
        files: ^scripts/
        exclude: ^scripts/node_modules

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-merge-conflict
        name: Check for unresolved merge conflict strings

  - repo: https://github.com/prettier/pre-commit
    rev: v2.1.1
    hooks:
      - id: prettier
        files: '^place/.*\.|tsx|jsx|js|ts]$'
