name: Codestyle and Linting

on:
    push:
    pull_request:
        types: [assigned, opened, synchronize, reopened]

jobs:
    codestyle:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Linting
              run: |
                  pip install pre-commit
                  pre-commit run --all-files
